# Generated by Django 4.0.6 on 2022-08-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_users_login1_users_reg1_delete_users_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_reg1',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
