# Generated by Django 4.0.6 on 2022-08-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_users_reg1_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_login1',
            old_name='uid',
            new_name='u_id',
        ),
    ]
