# Generated by Django 4.0.6 on 2022-08-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_uid_users_login1_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_login1',
            name='u_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.users_reg1'),
        ),
    ]
