# Generated by Django 4.0.6 on 2022-08-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_users_login1_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_login1',
            name='u_id',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='app1.users_reg1'),
            preserve_default=False,
        ),
    ]
