# Generated by Django 4.0.6 on 2022-08-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_users_login1_u_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='users_reg',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('depart', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='users_login1',
        ),
        migrations.DeleteModel(
            name='users_reg1',
        ),
        migrations.AddField(
            model_name='users_login',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.users_reg'),
        ),
    ]
