# Generated by Django 4.0.6 on 2022-08-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_users_login_users_reg_delete_users_login1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_login',
            old_name='u_id',
            new_name='uid',
        ),
    ]
