# Generated by Django 4.0.6 on 2022-08-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_users_reg_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_login',
            name='id',
        ),
        migrations.AlterField(
            model_name='users_login',
            name='uid2',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
