# Generated by Django 4.0.6 on 2022-09-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_users_login_id_alter_users_login_uid2'),
    ]

    operations = [
        migrations.CreateModel(
            name='type',
            fields=[
                ('T_id', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('I_id', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=15)),
                ('price', models.IntegerField(max_length=10)),
                ('stock', models.IntegerField(max_length=10)),
                ('T_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.type')),
            ],
        ),
    ]
