# Generated by Django 4.0.6 on 2022-09-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_type_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
