# Generated by Django 4.0.6 on 2022-09-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_department_items_image_alter_items_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_reg',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department'),
        ),
    ]
