# Generated by Django 4.0.6 on 2022-09-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_users_reg_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
