# Generated by Django 4.0.6 on 2022-09-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_type_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='s_items',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='I_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='type',
            name='T_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
