# Generated by Django 4.0.6 on 2022-09-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_s_items_alter_items_i_id_alter_type_t_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_reg',
            name='depart',
            field=models.CharField(max_length=30),
        ),
    ]
