# Generated by Django 4.0.6 on 2022-09-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_users_reg_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_items',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%m'),
        ),
    ]
