# Generated by Django 4.0.6 on 2022-09-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_s_items_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='T_id',
            new_name='Type',
        ),
    ]
