# Generated by Django 4.0.6 on 2022-09-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_department_depart_alter_items_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
