# Generated by Django 4.0.6 on 2022-09-23 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_staff_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='person',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='app1.staff_reg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='s_items',
            name='person',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='app1.staff_reg'),
            preserve_default=False,
        ),
    ]
