# Generated by Django 4.0.6 on 2022-09-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_items_type_remove_s_items_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='person',
        ),
        migrations.AddField(
            model_name='items',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.type'),
        ),
    ]
