# Generated by Django 4.0.6 on 2022-09-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_items_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.staff_reg'),
        ),
    ]
