# Generated by Django 4.0.6 on 2022-09-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_s_items_person_alter_items_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='items1',
            fields=[
                ('I_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=15, unique=True)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='items/%m')),
            ],
        ),
        migrations.CreateModel(
            name='type1',
            fields=[
                ('T_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15, unique=True)),
                ('image', models.ImageField(null=True, upload_to='types/%m')),
            ],
        ),
        migrations.RenameModel(
            old_name='department',
            new_name='department1',
        ),
        migrations.RenameModel(
            old_name='s_items',
            new_name='s_items1',
        ),
        migrations.RenameModel(
            old_name='users_login',
            new_name='users_login1',
        ),
        migrations.RenameModel(
            old_name='users_reg',
            new_name='users_reg1',
        ),
        migrations.RenameModel(
            old_name='staff_reg',
            new_name='staff_reg1',
        ),
        migrations.DeleteModel(
            name='items',
        ),
        migrations.DeleteModel(
            name='type',
        ),
        migrations.AddField(
            model_name='items1',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.type1'),
        ),
        migrations.AddField(
            model_name='items1',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.staff_reg1'),
        ),
    ]
