# Generated by Django 4.0.6 on 2022-09-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_items1_type1_rename_department_department1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items1',
            name='person',
        ),
        migrations.RemoveField(
            model_name='s_items1',
            name='person',
        ),
    ]
