# Generated by Django 4.0.6 on 2022-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_remove_items1_person_remove_s_items1_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items1',
            name='image',
            field=models.ImageField(null=True, upload_to='items/%y'),
        ),
        migrations.AlterField(
            model_name='type1',
            name='image',
            field=models.ImageField(null=True, upload_to='types/%y'),
        ),
    ]
