# Generated by Django 4.0.6 on 2022-09-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_alter_items1_image_alter_type1_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items1',
            name='Type',
        ),
        migrations.DeleteModel(
            name='s_items1',
        ),
        migrations.DeleteModel(
            name='items1',
        ),
    ]
