# Generated by Django 4.0.6 on 2022-09-23 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_remove_items1_type_delete_s_items1_delete_items1'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('I_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=15, unique=True)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='s_items',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=15, unique=True)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='s_items/%m')),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('T_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15, unique=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.RenameModel(
            old_name='department1',
            new_name='department',
        ),
        migrations.RenameModel(
            old_name='staff_reg1',
            new_name='staff_reg',
        ),
        migrations.RenameModel(
            old_name='users_login1',
            new_name='users_login',
        ),
        migrations.RenameModel(
            old_name='users_reg1',
            new_name='users_reg',
        ),
        migrations.DeleteModel(
            name='type1',
        ),
        migrations.AddField(
            model_name='items',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.type'),
        ),
    ]
