# Generated by Django 4.0.6 on 2022-10-03 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_staff_reg_type_teachers_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='I_id',
            new_name='Items_id',
        ),
        migrations.RenameField(
            model_name='s_items',
            old_name='s_id',
            new_name='special_id',
        ),
        migrations.RenameField(
            model_name='staff_reg',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='staff_reg',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='T_id',
            new_name='Type_id',
        ),
        migrations.RenameField(
            model_name='users_reg',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users_reg',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
