# Generated by Django 4.0.6 on 2022-10-09 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_i_id_items_items_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_reg',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='cart1',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('person', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.items')),
            ],
        ),
    ]
