# Generated by Django 4.0.6 on 2022-10-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_staff_reg_mobile_cart1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart1',
            old_name='stock',
            new_name='quantity',
        ),
    ]
