# Generated by Django 4.0.6 on 2022-10-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_stock_cart1_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart1',
            name='image',
            field=models.ImageField(null=True, upload_to='cart/%m'),
        ),
    ]
