# Generated by Django 4.0.6 on 2022-10-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_cart1_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart1',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart1',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
