# Generated by Django 4.0.6 on 2022-10-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cart1_total_alter_cart1_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='s_items',
        ),
    ]
