# Generated by Django 4.0.6 on 2022-11-20 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderplaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.users_login')),
            ],
        ),
    ]
